version: '3'

services:
  odoo:
    build: .
    container_name: odoo-tut
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
      - DB_PORT=5432
    depends_on:
      - odoo-db
    volumes:
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-network

  odoo-db:
    image: postgres:13
    container_name: odoo-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

volumes:
  odoo-db-data:

networks:
  odoo-network:
    driver: bridge
